name: CI

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    # using Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Run install
        uses: borales/actions-yarn@v4 
        with:
          cmd: install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod # will run `yarn build:prod` command

      - name: Deploy to my EC2 instance
        uses: easingthems/ssh/deploy@2.1.5
        with: 
          SSH_PRIVATE_KEY: $ {{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "dist/graduate-recruit-portal-client-app"
          REMOTE_HOST: "ec2-remote-host"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/html/graduate-recruit-portal-client-app"
